version: "3.3"
services:
  postgres:
    image: "postgres"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
volumes:
  my_postgres_data:
